-- =====================================================
-- PARTE 1: ÁNGULOS (EXTERIOR E INTERIOR)
-- subcategoria_id: 14 = Angulos
-- =====================================================

INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWEF7', 'ANGULO EXTERIOR 2,90M COLOR CENIZA', 'ANGULOS PARA WALLPANEL EXTERIOR', 14, 10, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWEF8', 'ANGULO EXTERIOR X2,90M COLOR VINOTINTO', 'ANGULOS PARA WALLPANEL EXTERIOR', 14, 10, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWEF9', 'ANGULO EXTERIOR COLOR BROWM 50*50*2900MM', 'ANGULOS PARA WALLPANEL EXTERIOR', 14, 10, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWEF1', 'ANGULO EXTERIOR 2,90M COLOR MARRÓN AMARILLO', 'ANGULOS PARA WALLPANEL EXTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWEF2', 'ANGULO EXTERIOR 2,90M COLOR CAFÉ', 'ANGULOS PARA WALLPANEL EXTERIOR', 14, 10, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWEF3', 'ANGULO EXTERIOR 2,90M COLOR PÚRPURA', 'ANGULOS PARA WALLPANEL EXTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWEF4', 'ANGULO EXTERIOR X2,90M COLOR TECA CLARO', 'ANGULOS PARA WALLPANEL EXTERIOR', 14, 10, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWEF5', 'ANGULO EXTERIOR 2,90M COLOR TECA OSCURO', 'ANGULOS PARA WALLPANEL EXTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWEF6', 'ANGULO EXTERIOR 2,90M COLOR GRIS PLATA', 'ANGULOS PARA WALLPANEL EXTERIOR', 14, 10, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWI24', 'ANGULO INTERIOR 2,90M COLOR ROYAL OAK', 'ANGULOS PARA WALLPANEL INTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWI15', 'ANGULO INTERIOR 2,90M COLOR MATT WHITE', 'ANGULOS PARA WALLPANEL INTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWI32', 'ANGULO INTERIOR 2,90M COLOR SILVER OAK', 'ANGULOS PARA WALLPANEL INTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWI21', 'ANGULO INTERIOR 2,90M COLOR DREAM SPACE', 'ANGULOS PARA WALLPANEL INTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWI31', 'ANGULO INTERIOR 2,90M COLOR TECNICAL WOODY', 'ANGULOS PARA WALLPANEL INTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWI16', 'ANGULO INTERIOR 2,90M COLOR MOCHA GRAY', 'ANGULOS PARA WALLPANEL INTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWI25', 'ANGULO INTERIOR 2,90M COLOR HOME PERFUME', 'ANGULOS PARA WALLPANEL INTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWI20', 'ANGULO INTERIOR 2,90M COLOR GOLDEN WIND', 'ANGULOS PARA WALLPANEL INTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWI30', 'ANGULO INTERIOR 2,90M COLOR STRAIGTH LOVE VENICE', 'ANGULOS PARA WALLPANEL INTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWI17', 'ANGULO INTERIOR 2,90M COLOR APPLE WOODY', 'ANGULOS PARA WALLPANEL INTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWI18', 'ANGULO INTERIOR 2,90M COLOR CEMENTE GRAY', 'ANGULOS PARA WALLPANEL INTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWI26', 'ANGULO INTERIOR 2,90M COLOR SCIENCIA TECHNOLOGY', 'ANGULOS PARA WALLPANEL INTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWI27', 'ANGULO INTERIOR 2,90M COLOR COMOLU', 'ANGULOS PARA WALLPANEL INTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWI19', 'ANGULO INTERIOR 2,90M COLOR QUI GUANGYAN', 'ANGULOS PARA WALLPANEL INTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWI29', 'ANGULO INTERIOR 2,90M COLOR STRAIGTH GRAIN PONE', 'ANGULOS PARA WALLPANEL INTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWI22', 'ANGULO INTERIOR 2,90M COLOR ROSEWOOD', 'ANGULOS PARA WALLPANEL INTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWI28', 'ANGULO INTERIOR 2,90M COLOR SLIKA CLOTH2', 'ANGULOS PARA WALLPANEL INTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-AWI23', 'ANGULO INTERIOR 2,90M COLOR CLASICAL TECHNOLOGY', 'ANGULOS PARA WALLPANEL INTERIOR', 14, 3, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;

SELECT COUNT(*) as total_productos FROM productos;
SELECT 'PARTE 1 COMPLETADA - 27 angulos insertados' as status;
