-- =====================================================
-- PARTE 2: ACCESORIOS Y DETERMINACIONES
-- subcategoria_id: 10 = Accesorios, 13 = Determinaciones
-- =====================================================

INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-CLCR', 'CLAVOS PARA CIELO RASO PAQ 1*100', 'ACCESORIOS PARA TECHO', 10, 10, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-CLIPS02', 'CLIPS PARA EXTERIOR WALL PANELL', 'ACCESORIO WALLPANEL', 10, 20, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-CLIPS03', 'ACCESORIO', 'ACCESORIO WALLPANEL', 10, 20, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-ASPE01', 'ACCESORIOS SEPARADOR ESPACIO', 'ACCESORIO WALLPANEL', 10, 1, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTWPS01 SMALL', 'DETERMINACION PS SMALLGRAY CLARO M02-06148 12*2900 MM', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTWEXT01', 'DETERMINACION WALL PANEL EXT', 'DETERMINACION WALL PANEL EXTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTW26', 'DETERMINACION WALL PANEL INTERIOR 16,5CMX2,90M COLOR JAZZ WHITE', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 10, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTW33', 'DETERMINACION WALL PANEL INTERIOR BLACK FIRE 40*24*2900MM', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTW01', 'DETERMINACION WPC WALL PANEL', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTW31', 'DETERMINACION WALL PANEL INTERIOR 16.50CM*2,90M COLOR TECNICAL WOODY', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTW32', 'DETERMINACION WALL PANEL INTERIOR 16,5CMX2,90M COLOR SILVER OAK', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTW15', 'DETERMINACION WALL PANEL INTERIOR 16.50CM*2,90M COLOR JAZZ', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTW19', 'DETERMINACION WALL PANEL INTERIOR 16.50CM*2,90M COLOR QUI GUANGYAN', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTW25', 'DETERMINACION WALL PANEL INTERIOR 16,5CMX2,90M COLOR HOME PERFUME', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTW34', 'DETERMINACION WALL PANEL INT LIGTH GRAY TECH WOOD 40*24*2900MM', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTWPS04 SMALL', 'DETERMINACION PS SMALL GRAY INTERMEDIO M02-22016 12*2900 MM', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTWPS01 BIG', 'DETERMINACION PS BIGGRAY CLARO M02-06148 12*2900 MM', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTWPS03 BIG', 'DETERMINACION PS BIGMARRON CLARO M02-5487-1 12*2900 MM', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTWPS04 BIG', 'DETERMINACION PS GRAY INTERMEDIO M02-22016 12*2900 MM', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTWPS02 BIG', 'DETERMINACION PS M02-23038-4 MARRON OSCURO 12*2900 MM', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTWPS02 SMALL', 'DETERMINACION PS SMALL GRAY CLARO M02-06148 12*2900 MM', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTWPS03 SMALL', 'DETERMINACION PS SMALL MARRON CLARO M02-5487-1 12*2900 MM', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTW36', 'DETERMINACION WALL PANEL INT LIGHT PARTEM40*24*2900MM', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTW35', 'DETERMINACION WALL PANEL INT SENSATION GRAY 40*24*2900MM', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTW38', 'DETERMINACION WALL PANEL INT TECH GOOD 01 40*24*2900MM', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) VALUES ('HC-DTW30', 'DETERMINACION WALL PANEL INTERIOR BLACK FIRE 40*24*2900MM', 'DETERMINACION DE WALLPANEL INTERIOR', 13, 5, 0, 0, true) ON CONFLICT (codigo) DO NOTHING;

SELECT COUNT(*) as total_productos FROM productos;
SELECT 'PARTE 2 COMPLETADA - Accesorios y Determinaciones insertados' as status;
