-- =====================================================
-- PARTE 2: ACCESORIOS Y DETERMINACIONES
-- =====================================================

-- ACCESORIOS
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-CLCR', 'CLAVOS PARA CIELO RASO PAQ 1*100', 'ACCESORIOS PARA TECHO', id, 10, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%accesorio%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-CLIPS02', 'CLIPS PARA EXTERIOR WALL PANELL', 'ACCESORIO WALLPANEL', id, 20, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%accesorio%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-CLIPS03', 'ACCESORIO', 'ACCESORIO WALLPANEL', id, 20, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%accesorio%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-ASPE01', 'ACCESORIOS SEPARADOR ESPACIO', 'ACCESORIO WALLPANEL', id, 1, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%accesorio%' LIMIT 1;

-- DETERMINACIONES
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTWPS01 SMALL', 'DETERMINACION PS SMALLGRAY CLARO M02-06148 12*2900 MM', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTWEXT01', 'DETERMINACION WALL PANEL EXT', 'DETERMINACION WALL PANEL EXTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTW26', 'DETERMINACION WALL PANEL INTERIOR 16,5CMX2,90M COLOR JAZZ WHITE', 'DETERMINACION DE WALLPANEL INTERIOR', id, 10, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTW33', 'DETERMINACION WALL PANEL INTERIOR BLACK FIRE 40*24*2900MM', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTW01', 'DETERMINACION WPC WALL PANEL', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTW31', 'DETERMINACION WALL PANEL INTERIOR 16.50CM*2,90M COLOR TECNICAL WOODY', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTW32', 'DETERMINACION WALL PANEL INTERIOR 16,5CMX2,90M COLOR SILVER OAK', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTW15', 'DETERMINACION WALL PANEL INTERIOR 16.50CM*2,90M COLOR JAZZ', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTW19', 'DETERMINACION WALL PANEL INTERIOR 16.50CM*2,90M COLOR QUI GUANGYAN', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTW25', 'DETERMINACION WALL PANEL INTERIOR 16,5CMX2,90M COLOR HOME PERFUME', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTW34', 'DETERMINACION WALL PANEL INT LIGTH GRAY TECH WOOD 40*24*2900MM', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTWPS04 SMALL', 'DETERMINACION PS SMALL GRAY INTERMEDIO M02-22016 12*2900 MM', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTWPS01 BIG', 'DETERMINACION PS BIGGRAY CLARO M02-06148 12*2900 MM', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTWPS03 BIG', 'DETERMINACION PS BIGMARRON CLARO M02-5487-1 12*2900 MM', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTWPS04 BIG', 'DETERMINACION PS GRAY INTERMEDIO M02-22016 12*2900 MM', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTWPS02 BIG', 'DETERMINACION PS M02-23038-4 MARRON OSCURO 12*2900 MM', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTWPS02 SMALL', 'DETERMINACION PS SMALL GRAY CLARO M02-06148 12*2900 MM', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTWPS03 SMALL', 'DETERMINACION PS SMALL MARRON CLARO M02-5487-1 12*2900 MM', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTW36', 'DETERMINACION WALL PANEL INT LIGHT PARTEM40*24*2900MM', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTW35', 'DETERMINACION WALL PANEL INT SENSATION GRAY 40*24*2900MM', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTW38', 'DETERMINACION WALL PANEL INT TECH GOOD 01 40*24*2900MM', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-DTW30', 'DETERMINACION WALL PANEL INTERIOR BLACK FIRE 40*24*2900MM', 'DETERMINACION DE WALLPANEL INTERIOR', id, 5, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%determinacion%' OR nombre ILIKE '%perfil%' LIMIT 1;

-- Verificar
SELECT COUNT(*) as total_productos FROM productos;
SELECT 'PARTE 2 COMPLETADA - Accesorios y Determinaciones insertados' as status;
