-- =====================================================
-- PARTE 4: LÁMINAS (PVC, WPC, BAMBOO)
-- =====================================================

-- LÁMINAS PVC
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-LPVC7', 'LAMINA DE PCV 3 MARMOLIZADO GRIS -DORADO', 'ACCESORIOS PISO', id, 35, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%lamina%pvc%' OR nombre ILIKE '%pvc%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-LPVC4', 'LAMINAS PVC MARMOLIZADA BLANCO CARRARA', 'LAMINA DE PVC', id, 35, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%lamina%pvc%' OR nombre ILIKE '%pvc%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-LPVC3', 'LAMINAS PVC WHITE 1.22MX2.44M', 'LAMINA DE PVC', id, 35, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%lamina%pvc%' OR nombre ILIKE '%pvc%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-LPVC8', 'LAMINAS PVC MARMOLIZADA BLANCO ARENA DY2420', 'ACCESORIOS PISO', id, 35, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%lamina%pvc%' OR nombre ILIKE '%pvc%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-LPVC1', 'LAMINAS PVC BLACK 1.22MX2.44M', 'LAMINA DE PVC', id, 35, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%lamina%pvc%' OR nombre ILIKE '%pvc%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-LPVC5', 'LAMINA PVC BLANCO CARRARA', 'LAMINA DE PVC', id, 35, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%lamina%pvc%' OR nombre ILIKE '%pvc%' LIMIT 1;

-- LÁMINAS WPC
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-LWPC01', 'LAMINA WPC ESPEJO SILVER 1220*24405MM', 'LAMINA DE WPC', id, 35, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%lamina%wpc%' OR nombre ILIKE '%wpc%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-WPC03', 'LAMINA WPCWPC ESPEJO GRIS MATE 1220*24405MM', 'LAMINA DE WPC', id, 45, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%lamina%wpc%' OR nombre ILIKE '%wpc%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-WPC02', 'LAMINA WPC ESPEJO BRONCE 1220*24405MM', 'LAMINA DE WPC', id, 45, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%lamina%wpc%' OR nombre ILIKE '%wpc%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-WPC01', 'LAMINA WPC ESPEJO SILVER1220*24405MM', 'LAMINA DE WPC', id, 45, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%lamina%wpc%' OR nombre ILIKE '%wpc%' LIMIT 1;

-- LÁMINAS BAMBOO
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-LB05', 'LAMINA BAMBOO 8CM*12.20CM*2.44M', 'LAMINA DE BAMBOO', id, 40, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%bamboo%' OR nombre ILIKE '%bambu%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-LB03', 'LAMINA BAMBOO 8CM*12.20CM*2.44M', 'LAMINA DE BAMBOO', id, 40, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%bamboo%' OR nombre ILIKE '%bambu%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-LB06', 'LAMINA BAMBOO 8CM*12.20CM*2.44M', 'LAMINA DE BAMBOO', id, 40, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%bamboo%' OR nombre ILIKE '%bambu%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-LB02', 'LAMINA BAMBOO 8CM*12.20CM*2.44M', 'LAMINA DE BAMBOO', id, 40, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%bamboo%' OR nombre ILIKE '%bambu%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-LB01', 'LAMINA BAMBOO 8CM*12.20CM*2.44M', 'LAMINA DE BAMBOO', id, 40, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%bamboo%' OR nombre ILIKE '%bambu%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-LBE01', 'LAMINA DE BAMBOO TIPO ESPEJO 1220X2440X5MM', 'LAMINA DE BAMBOO', id, 45, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%bamboo%' OR nombre ILIKE '%bambu%' LIMIT 1;

-- MADERA
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-MACH-6CM', 'MACHIHEMBRADO DE TECA (6CM)', 'MACHIMBRADO DE TECA', id, 8, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%madera%' OR nombre ILIKE '%machimbrado%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-MACH-8CM', 'MACHIHEMBRADO DE TECA 8CM', 'MACHIMBRADO DE TECA', id, 8, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%madera%' OR nombre ILIKE '%machimbrado%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-MDTECA31', 'MADERA ASERRADA TECA (TECTONA GRANDIS) M3', 'MADERA ASERRADA', id, 1, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%madera%' LIMIT 1;

-- PAPEL TAPIZ
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA014', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 2, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA080', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 2, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA083', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 2, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA082', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 2, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA005', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 2, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA047', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 2, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA065', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 2, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA077', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 2, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA066', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 2, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA087', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 2, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA002', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 2, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA007', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 2, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA081', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 2, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA001', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 2, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA046', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 2, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA004', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 2, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA078', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 2, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA076', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 2, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA058', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 2, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;
INSERT INTO productos (codigo, nombre, descripcion, subcategoria_id, stock, precio_detal, precio_mayor, activo) SELECT 'HC-PTMA003', 'PAPEL TAPIZ 600X3000MM', 'PAPEL TAPIZ', id, 3, 0, 0, true FROM subcategorias WHERE nombre ILIKE '%papel%tapiz%' OR nombre ILIKE '%tapiz%' LIMIT 1;

-- Verificar
SELECT COUNT(*) as total_productos FROM productos;
SELECT 'PARTE 4 COMPLETADA - Láminas, Madera y Papel Tapiz insertados' as status;
